# Generated by Django 2.2.2 on 2019-06-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='number_of_employee',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_category',
            field=models.ManyToManyField(to='vendors.VendorCategory'),
        ),
    ]
