# Generated by Django 2.2.2 on 2019-06-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20190622_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_category',
            field=models.ManyToManyField(blank=True, null=True, to='vendors.VendorCategory'),
        ),
    ]
