# Generated by Django 2.2.2 on 2019-06-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20190623_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_category',
        ),
        migrations.DeleteModel(
            name='VendorCategory',
        ),
    ]
